services:

  service-configuration:
    build:
      context: ./config
    volumes:
      - syslog:/var/log
      - service-config:/config

  selv-v3-extensions:
    image: openlmismz/selv-v3-extensions-config:${OL_SELV_V3_EXTENSION_VERSION}
    volumes:
      - selv-v3-extensions-stockmanagement:/extensions-stockmanagement
      - selv-v3-extensions-fulfillment:/extensions-fulfillment

  consul:
    image: hashicorp/consul:${OL_CONSUL_VERSION}
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 30s
      timeout: 5s
      retries: 20
    logging: &logging
      driver: json-file
      options:
        max-size: "50m"
        max-file: "7"

  db:
    image: openlmis/postgres:${OL_POSTGRES_VERSION}
    env_file: settings.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - olmis-db
    depends_on:
      consul:
        condition: service_healthy
    logging:
      <<: *logging

  log:
    restart: always
    image: openlmis/rsyslog:${OL_RSYSLOG_VERSION}
    volumes:
      - syslog:/var/log
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
    logging:
      <<: *logging

  scalyr:
    restart: always
    image: openlmis/scalyr:${OL_SCALYR_AGENT_VERSION}
    container_name: scalyr-agent
    env_file: settings.env
    volumes:
      - service-config:/config
      - /run/docker.sock:/var/scalyr/docker.sock
      - syslog:/var/log
      - nginx-log:/var/log/nginx/log
      - auth-tomcat-log:/var/log/auth-tomcat
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
    logging:
      <<: *logging

  redis:
    image: redis:3.2.12
    depends_on:
      consul:
        condition: service_healthy

  nginx:
    image: openlmis/nginx:${OL_NGINX_VERSION}
    ports:
      - "${OL_HTTP_PORT:-80}:80"
    env_file: settings.env
    entrypoint: >
      sh -c "cp -f /config/nginx/openlmis.conf /etc/consul-template/openlmis.conf
      && sh /home/run.sh"
    environment:
      NGINX_LOG_DIR: '/var/log/nginx/log'
    volumes:
      - nginx-log:/var/log/nginx/log
      - consul-template-log:/var/log/consul-template
      - service-config:/config
    depends_on:
      consul:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    logging:
      <<: *logging

  reference-ui:
    image: openlmismz/selv-v3-ui:${SELV_V3_UI_VERSION}
    env_file: settings.env
    depends_on:
      consul:
        condition: service_healthy
      # Services from which data is being taken during logging in
      referencedata:
        condition: service_healthy
#      auth:
#        condition: service_healthy
#      notification:
#        condition: service_healthy
#      report:
#        condition: service_healthy
#      fulfillment:
#        condition: service_healthy
      stockmanagement:
        condition: service_healthy
    logging:
      <<: *logging

  ftp:
    image: driesva/proftpd
    ports:
      - "${OL_FTP_PORT_21:-21}:21"
      - "${OL_FTP_PORT_20:-20}:20"
    env_file: settings.env
    depends_on:
      consul:
        condition: service_healthy

  requisition:
    restart: always
    image: openlmis/requisition:${OL_REQUISITION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms1024m
        -Xmx1024m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
#    healthcheck:
#      test: "wget --spider http://localhost:8080/actuator/health || exit 1"
#      interval: 30s
#      timeout: 5s
#      retries: 20
    logging:
      <<: *logging

  referencedata:
    restart: always
    image: openlmis/referencedata:${OL_REFERENCEDATA_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms1536m
        -Xmx1536m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
    healthcheck:
      test: "wget --spider http://localhost:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 5s
      retries: 20
    logging:
      <<: *logging

  auth:
    restart: always
    image: openlmis/auth:${OL_AUTH_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms1024m
        -Xmx1024m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
#    healthcheck:
#      test: "wget --spider http://localhost:8080/actuator/health || exit 1"
#      interval: 30s
#      timeout: 5s
#      retries: 20
    logging:
      <<: *logging

  notification:
    restart: always
    image: openlmis/notification:${OL_NOTIFICATION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
#    healthcheck:
#      test: "wget --spider http://localhost:8080/actuator/health || exit 1"
#      interval: 30s
#      timeout: 5s
#      retries: 20
    logging:
      <<: *logging

  fulfillment:
    restart: always
    image: openlmis/fulfillment:${OL_FULFILLMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms1024m
        -Xmx1024m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
      - selv-v3-extensions-fulfillment:/extensions
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      selv-v3-extensions:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
#    healthcheck:
#      test: "wget --spider http://localhost:8080/actuator/health || exit 1"
#      interval: 30s
#      timeout: 5s
#      retries: 20
    logging:
      <<: *logging

  stockmanagement:
    restart: always
    image: openlmis/stockmanagement:${OL_STOCKMANAGEMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms2048m
        -Xmx2048m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
      - selv-v3-extensions-stockmanagement:/extensions
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      selv-v3-extensions:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
    healthcheck:
      test: "wget --spider http://localhost:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 5s
      retries: 20
    logging:
      <<: *logging

  report:
    image: openlmismz/selv-v3-report:${SELV_V3_REPORT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms2048m
        -Xmx2048m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
#    healthcheck:
#      test: "wget --spider http://localhost:8080/actuator/health || exit 1"
#      interval: 30s
#      timeout: 5s
#      retries: 20
    logging:
      <<: *logging

  cce:
    restart: always
    image: openlmis/cce:${OL_CCE_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
    logging:
      <<: *logging

  buq:
    restart: always
    image: openlmis/buq:${OL_BUQ_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
    logging:
      <<: *logging

  hapifhir:
    restart: always
    image: openlmis/hapifhir:${OL_HAPIFHIR_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
    logging:
      <<: *logging

  diagnostics:
    restart: always
    image: openlmis/diagnostics:${OL_DIAGNOSTICS_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
    logging:
      <<: *logging

  # SELV-specific

  dhis2-integration:
    restart: always
    image: openlmismz/selv-v3-dhis2-integration:${OL_DHIS2_INTEGRATION_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
    logging:
      <<: *logging

  equipment:
    image: openlmismz/equipment:${OL_EQUIPMENT_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
    logging:
      <<: *logging

  requisition-batch:
    image: openlmismz/requisition-batch:${OL_REQUISITION_BATCH_VERSION}
    env_file: settings.env
    environment:
      JAVA_OPTS: >-
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
        -Dlogging.config=/config/log/logback.xml
    volumes:
      - syslog:/var/log
      - service-config:/config:ro
    depends_on:
      service-configuration:
        condition: service_completed_successfully
      consul:
        condition: service_healthy
      log:
        condition: service_started
    logging:
      <<: *logging

volumes:
  service-config:
  syslog:
  nginx-log:
  auth-tomcat-log:
  consul-template-log:
  selv-v3-extensions-stockmanagement:
  selv-v3-extensions-fulfillment:
  pgdata:
    external: true
